%global commit 4d89274db70797b72522611b7dcd16ddb5ebacd9
%global shortcommit %(c=%{commit}; echo ${c:0:7})

Name:           dsi-studio
Version:        0.1
Release:        0.1.git%{shortcommit}%{?dist}
Summary:        Diffusion MRI analysis tool

License:        BSD
URL:            http://dsi-studio.labsolver.org/
Source0:        https://github.com/frankyeh/DSI-Studio/archive/%{commit}/%{name}-%{shortcommit}.tar.gz
Patch0:         0001-link-against-libsvm-due-to-system-TIPL.patch

BuildRequires:  gcc-c++
BuildRequires:  qt5-qtbase-devel
BuildRequires:  boost-devel
BuildRequires:  zlib-devel
BuildRequires:  mesa-libGLU-devel
BuildRequires:  tipl-devel

%description
DSI Studio is an open source diffusion MRI analysis tool. It has been used in
several human and animal studies to map brain connections and correlate
diffusion MRI findings with diseases. It provides the following functions:

Reconstruction

* Diffusion tensor imaging (DTI)
* Q-ball imaging (QBI) using Funk-Radon transform or Spherical hormonic based
  transformation
* Diffusion spectrum imaging (DSI)
* Generalized Q-sampling Imaging (GQI)
* Diffusion Deconvolution
* Q-space Diffeomorphic Reconstruction (QSDR)

Tractography

* Streamline fiber tracking
* Supported file format for input ROI: text file, Analyze, NIFTI
* Supported file format for output tracts: text file, TrackVis .trk file,
  Matlab mat file
* Generate simulated images based on the bi-exponential model with
  user-specific b-tables

Analysis

* ROI based analysis: able to export the FA value, fiber directions and ADC of
  each voxel to text files or MAT files (for Matlab)
* Track specific analysis: able to obtain FA values according to track
  coordinates and export related information to text files or MAT files
  (for Matlab)
* All the result generated (DTI, QBI, DSI, tractography... etc) from DSI
  Studio can be directly imported by Matlab
* Load trk files generated by TrackVis

Coregistration

* Insert T1/T2 images in tractography by linear transform with mutual information as cost function

Visualization

* Real time 3D tractography presentation
* Tracks selection, deletion, cutting function
* 3D Regions presentation
* ODF visualization

%prep
%autosetup -n DSI-Studio-%{commit} -p1

mkdir build

%build
pushd build/
  %qmake_qt5 ../
  %make_build
popd

%install
install -p -D -m0755 build/dsi_studio %{buildroot}/%{_bindir}/dsi-studio

%files
%license COPYRIGHT
%doc readme.txt
%{_bindir}/%{name}

%changelog
* Sat Dec 12 2015 Igor Gnatenko Mi.gnatenko.brain@gmail.com> - 0.0-0.1.git4d89274
- Unbundle TIPL
- Fix trivial stuff in spec

* Tue Nov 24 2015 Morgan Hough <morgan.hough@gmail.com> 0.0-0
- Initial packaging
